### ISSUE TITLE
App laggy

### ISSUE THREAD

**Issue by yash-vaghela21** [react-native-admob/admob#10]
When AD loads the app is very choppy for some moment.
i have already initialised the `AdMob.initialize()` at app launch.

**Comment by wjaykim** [comment]
Hi, thank you for using this library. To find out what's wrong, let me show your code please.

**Comment by yash-vaghela21** [comment]
initialisation at root App.js

`  useEffect(() => {
    const init = async () => {
      await AdMob.initialize();
    };
    init();
  }, []);`
      
AD Code on my Home Page  - 

` <BannerAd
    size={'LARGE_BANNER'}
    unitId={unitID}
    onAdFailedToLoad={(error) => console.error(error)}
  />  `
  
  problem is that it's hang up for around 10 seconds only. then it work fine after AD rendered.

**Comment by wjaykim** [comment]
I need more detail. What platform are you experiencing lag, and what version of our package are you using?

**Comment by yash-vaghela21** [comment]
`"react": "17.0.1",`
`"react-native": "0.64.2",`
`"@react-native-admob/admob": "^1.0.1",`

i am facing this on Android side.i will try to send video also

**Comment by haivle** [comment]
I notice the app super laggy when transitioning between background and foreground. I think some audio sessions of the banners is not closed. U can test it by playing music in background and open the app. The audio from music app will be interrupted

**Comment by haivle** [comment]
In my case, using iOS simulator
1. showing the video ads on splash screen using useRewardedInterstitialAd hook
2. Close the video
3. navigate to another screen
-> the audio session is interupted
4. make app go to background mode 
-> audio of simulator is laggy, js and ui FPS is dropped to 0
5. make app to to foreground
-> notice animation fps is dropped

**Comment by haivle** [comment]
when I try to remove all functions and rewardedInterstitialAd from useEffect dependencies, the issue is improved. 
```
const load = useCallback((requestOptions = adRequestOptions) => {
    init();
    rewardedInterstitialAd.load(requestOptions).catch(e => setAdLoadError(e)).then(() => setAdLoaded(true));
  }, [adRequestOptions]);

  const show = useCallback(() => {
    if (adPresented) {
      console.warn('[RNAdMob(RewardedInterstitialAd)] Ad is already presented once.');
    } else if (adLoaded) {
      rewardedInterstitialAd.show().catch(e => setAdPresentError(e)).then(() => setAdPresented(true));
    } else {
      console.warn('[RNAdMob(RewardedInterstitialAd)] Ad is not loaded.');
    }
  }, [adPresented, adLoaded]);

  useEffect(() => {
    if (!rewardedInterstitialAd.requested && loadOnMounted) {
      load();
    }
  }, [loadOnMounted]);
  useEffect(() => {
    if (adLoaded && showOnLoaded) {
      show();
    }
  }, [adLoaded, showOnLoaded]);

  useEffect(() => {
    if (adDismissed && loadOnDismissed) {
      load();
    }
  }, [adDismissed, loadOnDismissed]);

  useEffect(() => {
    const presentListener = rewardedInterstitialAd.addEventListener('adPresented', () => setAdDismissed(false));
    const dismissListener = rewardedInterstitialAd.addEventListener('adDismissed', () => {
      setAdDismissed(true);
      init();
    });
    const rewardListener = rewardedInterstitialAd.addEventListener('rewarded', r => setReward(r));
    return () => {
      presentListener.remove();
      dismissListener.remove();
      rewardListener.remove();
    };
  }, []);
```

**Comment by wjaykim** [comment]
I'm investigating this issue's relation with audio.

**Comment by wjaykim** [comment]
Hi, I made some changes to code. Would you guys try version 1.1.0 and give me feedback? Thank you.

**Comment by yash-vaghela21** [comment]
issue solved for me.
closing it

**Comment by JeffGuKang** [comment]
In my case, `loadOnMounted: true` makes laggy. 

I solved the issue to use `loadOnMounted: false` option and load RewardedAd in `useEffect`.
