### ISSUE TITLE
Multiple appOpenAds at the same time

### ISSUE THREAD

**Issue by zoobibackups** [react-native-admob/admob#100]
**On resume app it is showing multiple appOpenAds at the same time.**

### Expected behavior

It should display single appOpenAd at one time.

### Actual behavior & steps to reproduce

Showing multiple ads at the same time when resume the app.

## Snack or minimal code example
```
import { AppOpenAdProvider } from '@react-native-admob/admob';

 <AppOpenAdProvider
      unitId={APP_OPEN_AD_ID}
      options={{showOnAppForeground: true }}
    >
      <App />
    </AppOpenAdProvider>
```

## Package versions
```
"@react-native-admob/admob": "^2.0.1",
"react": "17.0.2",
"react-native": "0.67.2",
"react-native-admob-native-ads": "^0.5.0"
```

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
