### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'.

### ISSUE THREAD

**Issue by alz10** [react-native-admob/admob#101]
## Description
Instaling the library on `"react-native": "0.66.4"` causes error. 
```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
     AAR metadata file: /Users/username/.gradle/caches/transforms-3/91a6b5abf3bec760d8c9a4797cfa8ae1/transformed/work-runtime-2.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.
```
## What i did so far
add `org.gradle.jvmargs=-Xmx4608m` in **gradle.properties**
add `multiDexEnabled true` in **app/build.gradle**
add `implementation 'com.google.android.gms:play-services-ads:20.6.0'` in  **dependencies > app/build.gradle**
Tried removing the library and build was successful

## Package versions

- React Native: "0.66.4"
- React Native AdMob: "^2.0.1"
- Device: M1 Mackbook Air

## Affected platforms

- [x] Android
- [ ] iOS

**Comment by grkemtneri** [comment]
@alz10 same issue, did you find any solution ?

**Comment by alz10** [comment]
> @alz10 same issue, did you find any solution ?

I'm actually just waiting for the latest release of `RN v0.68.0`.
Someone made the same issue, check it here https://github.com/react-native-admob/admob/issues/65

**Comment by alz10** [comment]
@grkemtneri  By the way, you can use this version if you're not using SDK 31 
`npm install @react-native-admob/admob@1.5.1 --save`
