### ISSUE TITLE
Delay SDK initialization to request EEA consent

### ISSUE THREAD

**Issue by scaralfred** [react-native-admob/admob#103]
How can we "delay" the sdk initialization and only initialize it when the consent was givem?
By law we should only collect EEA users personal data after they gave consent, but the sdk is loading at app a launch and it collects data by default.

**Comment by tarouboy** [comment]
Agree. Otherwise it may not be GDPR compliant.

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
