### ISSUE TITLE
[Suggestion] Disable entire admob

### ISSUE THREAD

**Issue by alz10** [react-native-admob/admob#104]
I made subscription feature in my app, obviously users can pay real $$$ and remove the ads. I wish there's a way in this library to disable all ads immediately right after buying the subscription or in-app purchase for `remove ads`. 

something like `disableEntireAdmob();` will do

**Comment by scaralfred** [comment]
I think there are various methods to "destroy ads" units. I suggest taking a deeper look at the docs...

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
