### ISSUE TITLE
Expo Supported?

### ISSUE THREAD

**Issue by gitnasr** [react-native-admob/admob#105]
I would like to know if it's supported by the expo. i read the docs but I didn't find any clue that's expo supported

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
