### ISSUE TITLE
Could not build

### ISSUE THREAD

**Issue by haivle** [react-native-admob/admob#12]
I've got this issue when trying to build from xcode(@react-native-admob/admob v1.0.3)

<img width="424" alt="Screen Shot 2021-08-18 at 4 04 33 pm" src="https://user-images.githubusercontent.com/52659811/129846441-fbb718a9-c2cd-412e-b442-f0fe4ebccf76.png">

**Comment by wjaykim** [comment]
Fixed in new version. Thank you for reporting.
