### ISSUE TITLE
App open Ad error

### ISSUE THREAD

**Issue by andkom** [react-native-admob/admob#20]
sometimes i get error:

```
{"code": 3, "message": "No ad config."}
```

code:

```
import {useEffect, useState} from 'react';
import AdMob, {useAppOpenAd} from '@react-native-admob/admob';

const useOpenAppAd = (unitId: string) => {
  const [initialized, setInitialized] = useState(false);

  useAppOpenAd(
    initialized ? unitId : null,
    {
      showOnColdStart: true,
      showOnAppForeground: true,
    },
  );

  useEffect(() => {
    (async () => {
      await AdMob.initialize();
      setInitialized(true);
    })();
  });
};

export default useOpenAppAd;

```

App.ts:

```
const App = () => {
  useOpenAppAd('ca-app-pub-....');

  return (
     ....
  );
};

```

**Comment by wjaykim** [comment]
https://support.google.com/admob/thread/66346434/error-3-no-ad-config-in-google-play-published-app?hl=en&msgid=66351379

**Comment by wjaykim** [comment]
Can you try find solution [here](https://stackoverflow.com/questions/33566485/failed-to-load-ad-3#:~:text=It%20Means%20that%20your%20code,will%20load%20the%20ads%20immediately.%5D)? I think this issue is not related to this library.

**Comment by andkom** [comment]
@wjaykim ok, thanks

**Comment by bilarslan** [comment]
Hello @andkom, found any solution?

**Comment by andkom** [comment]
@bilarslan not yet

**Comment by bilarslan** [comment]
Hello @andkom 
It looks like I solved the problem.  I saved my devices as test devices under admob dashboard from Settings > Test Devices. And I used my own admob unit ids, not the test ids so it solved 🎉🎉
