### ISSUE TITLE
Anyone using this on production?

### ISSUE THREAD

**Issue by tarouboy** [react-native-admob/admob#23]
As title. Would like to see is it production ready.
And to the author @wjaykim will you consider enabling the "Sponsor" button or link to [issuehunt](https://issuehunt.io/) or anything similar so someone like me who couldn't contribute on coding could help a little bit.

**Comment by vrchvngel** [comment]
@tarouboy I just created my first app and put it in the App Store. It works perfectly fine. I had to fill in the AdMob Payments and wait a few hours for serving ads. They served ads after the app was placed in the App Store. If Test Ads works in your project - it will work with real Unit ID too. Just remember about everything they write in AdMob Guide and it will be fine.

If you want to check how it looks, here's link to App Store:
https://apps.apple.com/us/app/never-have-i-ever-dirty/id1585131769

**Comment by tarouboy** [comment]
Someone asked similar question.
https://github.com/react-native-admob/admob/issues/25

I will close this one.
