### ISSUE TITLE
app stop responding when loadOnDismissed: true

### ISSUE THREAD

**Issue by alexandreolives** [react-native-admob/admob#24]
When useRewardedAd or useInterstitialAd are used with parameter loadOnDismissed: true,
the app becomes laggy after closing ads and any touchable element won't respond in time.

package version : 1.0.10
react version : 16.13.1 
react-native version :  0.63.4

**Comment by wjaykim** [comment]
Hi, thank you for reporting. Would you try version 1.1.0 and feedback me again? I made some changes to code.

**Comment by lewatt23** [comment]
I have the same error

    "@react-native-admob/admob": "^1.1.2",
    "react-native": "0.64.2",
    "react": "17.0.1",
