### ISSUE TITLE
Can we use this in production?

### ISSUE THREAD

**Issue by yash-vaghela21** [react-native-admob/admob#25]
is anyone using this in production?
i tried in production with Real UnitID and its giving error in AD LOAD FAILED. but error is also not specified.
my app is still not in playstore

**Comment by vrchvngel** [comment]
@ydv0121 I just created my first app and put it in the App Store. It works perfectly fine. I had to fill in the AdMob Payments and wait a few hours for serving ads. They served ads after the app was placed in the App Store. If Test Ads works in your project - it will work with real Unit ID too. Just remember about everything they write in AdMob Guide and it will be fine.

If you want to check how it looks, here's link to App Store:
https://apps.apple.com/us/app/never-have-i-ever-dirty/id1585131769

**Comment by mayconline** [comment]
in production it only works if the app is published in the play store, it can be in the internal test group

**Comment by yash-vaghela21** [comment]
will it work if payment is pending?
![Screenshot 2021-09-15 at 10 02 34 AM](https://user-images.githubusercontent.com/37238045/133371039-4a0e3d8a-0371-4ab7-8fa4-287034cd6c2a.png)

**Comment by tarouboy** [comment]
> in production it only works if the app is published in the play store, it can be in the internal test group

Not really. 
I have an app that provide standalone apk and published in Huawei AppGallery and still able to receive ads from admob.
