### ISSUE TITLE
Multiple sizes implementation in AdMobBanner can be improved

### ISSUE THREAD

**Issue by edodusi** [react-native-admob/admob#26]
When you want multiple sizes in AdManager Banner you call `<GAMBannerAd>` and pass the `sizes` attribute as an array.
However, the element has a mandatory `size` attribute: this is incorrect according to the SDK docs, in fact you should bu able to pass either a single size or an array of sizes.

The native implementation also leads to mixed results: the module calls `requestAd()` after both `setSize()` and `setSizes()`, but the `requestAd()` method only checks for the single `size` attribute to be non-null, so there's a race condition, if `setSize` gets called before `setSizes` you end up with a double call, one with a single size and one with multisize.

I needed the multisize feature for an app so I quickly fixed it for my own need, but I think the whole element should be refactored a bit to let a caller set multiple or single size and only perform one `requestAd()` call.

@wjaykim if you didn't already plan to change this behavior let me know and I will create a more robust PR soon as I can.

**Comment by wjaykim** [comment]
Hi, I am aware of this and `size` prop will be changed to nullable in future version. Thank you for reporting

**Comment by edodusi** [comment]
Thank you! Will check future releases for closing this one 😉

**Comment by wjaykim** [comment]
New version 1.1.0 is released and changes related to this is included.

**Comment by edodusi** [comment]
Thanks @wjaykim, just checked, I left you a comment on the related commit because you accidentally broke the types declaration file, anyway thanks for the great work!

**Comment by edodusi** [comment]
@wjaykim oops sorry I saw you fixed it in the next commit so nevermind 😅
