### ISSUE TITLE
Implementation with error

### ISSUE THREAD

**Issue by mayconline** [react-native-admob/admob#28]
in `android/buid.gradle` , ln 58 , I believe the array is inverted.

![image](https://user-images.githubusercontent.com/38052474/133349138-7cedf0cb-a333-42a0-87a4-6827473af4e8.png)

**Comment by wjaykim** [comment]
The expression means all versions >= 20.0 and < 21.0

**Comment by mayconline** [comment]
> The expression means all versions >= 20.0 and < 21.0

Thanks, I didn't know 🤝
