### ISSUE TITLE
Need guide to use on class component

### ISSUE THREAD

**Issue by segrokkroto** [react-native-admob/admob#29]
Hello,

I need help how to show InterstitialAd on class component, I try to read this doc https://react-native-admob.github.io/admob/docs/api/InterstitialAd but still confused.

help me with example ,please..

Thanks

**Comment by wjaykim** [comment]
Hi, sorry for late comment.
Hooks introduced in this library is written upon class instance ads for example, `InterstitialAd`.
You can refer to the [source](https://github.com/react-native-admob/admob/blob/master/src/hooks/useInterstitialAd.ts) of one of the hooks to see how to use class instance ad.
I know the source cannot give you full help to know how to apply it on class component; I'll update docs with working example in class components soon.

**Comment by wjaykim** [comment]
Now example code is included in example app.
