### ISSUE TITLE
useAppOpenAd blocks splash screen

### ISSUE THREAD

**Issue by andkom** [react-native-admob/admob#30]
When I exit app, it will still remain in task manager. If I reopen app again, Ad will never present, so `adDismissed`, `adLoadError` never change and splash screen never hides. If I force remove app from task manager before reopening again, everything works OK. Same behavior for `showOnAppForeground: true`.

The issue can be reproduced in the example app too.

**Comment by andkom** [comment]
Debug showed that `showAdIfAvailable()` fails silently because there is no `activity` and `presentPromise`:

RNAdMobAppOpenAdModule.java:
```
private void showAdIfAvailable() {
    Activity activity = getCurrentActivity();
    if (activity == null) {
        if (presentPromise != null) {
            presentPromise.reject("E_NULL_ACTIVITY", "App Open Ad attempted to load but the current Activity was null.");
            presentPromise = null;
        }
        return;
    }
    activity.runOnUiThread(() -> {
        if (appOpenAd != null && wasLoadTimeLessThanNHoursAgo(4)) {
            appOpenAd.show(activity);
        } else {
            requestAd(null);
            if (presentPromise != null) {
                presentPromise.reject("E_AD_NOT_READY", "Ad is not ready.");
                presentPromise = null;
            }
        }
    });
}
```

**Comment by andkom** [comment]
it seems it should use `ActivityLifecycleCallback` methods to track current activity
as done in https://github.com/thebylito/react-native-admob-appopen/blob/master/android/src/main/java/com/reactnativeadmobappopen/AppOpenManager.java

**Comment by wjaykim** [comment]
I'll work on this.

**Comment by wjaykim** [comment]
Hi, can you try 1.2.0 and give me a feedback?

**Comment by andkom** [comment]
@wjaykim bug is not fixed yet

**Comment by andkom** [comment]
`adDismissed` is now broken, it never changes to `true` on ad close...

**Comment by andkom** [comment]
@wjaykim still does't work in 1.5
