### ISSUE TITLE
Multiple InterstitialAds in one component?

### ISSUE THREAD

**Issue by quan2nd** [react-native-admob/admob#31]
I have multiple Interstitial IDs, is there a way I can use multiple InterstitialAds in one component?
Thank you.

**Comment by wjaykim** [comment]
Hi, sorry for late comment.

You can just use multiple hooks if you are using hook, or make multiple instances if you are using ad instances.

Example:
```js
const { adLoaded: adALoaded } = useInterstitialAd(UNIT_ID_A);
const { adLoaded: adBLoaded } = useInterstitialAd(UNIT_ID_B);
```

```js
const adA = InterstitialAd.createAd(UNIT_ID_A);
const adB = InterstitialAd.createAd(UNIT_ID_B);

adA.load();
adA.show();

adB.load();
...
```
