### ISSUE TITLE
app crashes on start

### ISSUE THREAD

**Issue by haresh4d** [react-native-admob/admob#35]
After installing this library my app crashes on start up. Please suggest some solution. 

Also provide solution to use this library and `react-native-admob-native-ads` library together.

**Comment by haresh4d** [comment]
Issue solved

**Comment by scottc5** [comment]
Did you find a solution?

**Comment by haresh4d** [comment]
You must provide app id in info.plist otherwise it will crash because admob is not initialised properly.
