### ISSUE TITLE
On iOs even if the showOnColdStart is false. The app shows the appOpenAd.

### ISSUE THREAD

**Issue by haresh4d** [react-native-admob/admob#37]
I do not want to show the app open ad when user first load the app. I only want to show it when the app comes to foreground. But this library loads the add and display it in startup also.

**Comment by haresh4d** [comment]
Is any one having same issue? @wjaykim @ifsnow @ahmetbicer do we have any solution for this? It happens in iOS.

**Comment by wjaykim** [comment]
Hi, I am refactoring codes and testing issues. I'll let you know when this issue is resolved.

**Comment by wjaykim** [comment]
Fixed in 1.2.0
