### ISSUE TITLE
Feature request : custom_targeting

### ISSUE THREAD

**Issue by manuhook** [react-native-admob/admob#38]
Thank you so much @wjaykim for this lib !

Can you please add custom_targeting for GAMBannerAd ?
https://developers.google.com/ad-manager/mobile-ads-sdk/android/targeting#custom_targeting
https://developers.google.com/admob/ios/api/reference/Classes/GAMRequest

Until now I was using sbugert/react-native-admob with this commit to support custom targeting on iOS & Android.
Maybe this work can help :
https://github.com/manuhook/react-native-admob/commit/48a9dfa400f08e1f00d618a970ce4ef6df013b6a

Thank again !

**Comment by wjaykim** [comment]
Hi, I'll add the options in the future release. Thank you for suggesting.

**Comment by manuhook** [comment]
Hi, thank you for your answer. It is now implemented on our project, you will have a PR soon !
