### ISSUE TITLE
appOpenAd comes in between

### ISSUE THREAD

**Issue by haresh4d** [react-native-admob/admob#39]
Even if I am using the app in real device appOpen is displayed. Its flooding with appOpen ads.

**Comment by haresh4d** [comment]
@wjaykim please find a solution to this. I have used this library in production and now I am in trouble. Please.

**Comment by wjaykim** [comment]
Hi, I'm sorry to hear this library didn't work well. I am working on my priority job these days and as the job completes, I will investigate issues within this library. Sorry again and please understand I'm in running out of time.

**Comment by wjaykim** [comment]
Hey @haresh4d, can you reproduce your issue with example code?

**Comment by wjaykim** [comment]
Try version 1.2.0 and open a new issue if it keep occurs.
