### ISSUE TITLE
How can I detect the Interstitial Ad is dismissed cause of the user's abusing?

### ISSUE THREAD

**Issue by marine1079** [react-native-admob/admob#41]
Reproduction: Interstitial Ad is shown > Go background (Home) > Tap App Icon > Interstitial Ad is dismissed (While showing)

Can it be possible to detect user's behavior that goes to background while ad is showing and then execute app by touching the App's icon for dismissing Interstitial ad immediately?

I used AppState of react native but in Android, the state is going to 'background' with Ad's showing and back to 'active' with Ad's dismissing so I couldn't detect user's additional/manual behavior to go out and in to App during the Ad is showing.

**Comment by wjaykim** [comment]
I'll try to find out solution for this.

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
