### ISSUE TITLE
message:"No ad config", "code:3"

### ISSUE THREAD

**Issue by Obhenimen** [react-native-admob/admob#48]
### Expected behavior
I expected to see a Banner Ad from admob

### Actual behavior & steps to reproduce
instead i got an error saying no ad config, code:3

## Snack or minimal code example
import React from 'react'
import { View, Text,Image, TouchableOpacity } from 'react-native'
import styles from './styles'
import { useNavigation } from '@react-navigation/native'
import { PAYMENT_PAGE } from '../../constants/routeNames'
import Icon from '../common/Icon'
import { BannerAd,TestIds,BannerAdSize} from '@react-native-admob/admob';

const CheckCoinComponent = ({coinamount,isPremium,showAds,name,daysLeft}) => {
    const {navigate} = useNavigation()
  //console.log(isPremium)
    return (
        <View style={styles.Container}>
            <View style={styles.viewone}>
                <View style={styles.viewonewrap}>
                <View>
                <BannerAd
                  size={BannerAdSize.ADAPTIVE_BANNER}
                  unitId={"ca-app-pub-7467526896400501/3262508535"}
                  onAdFailedToLoad={(error) => console.error(error)}
                  requestOptions={{
                    requestNonPersonalizedAdsOnly: true,
                  }}
                />
              </View>

## Package versions

- React Native: 0.64.2
- React Native AdMob:1.2.0
- Google Mobile Ads SDK(if specified):20.4.0
- Xcode:
- Java & Gradle:
Android gradle plugin: 4.2.2
gradle plugin version: 6.8.3
## Affected platforms
Android

**Comment by wjaykim** [comment]
Code 3 is related to your ad unit.

Possible cases are:
- May be your ad unit is not ready yet because it has just created.
- You didn't set up app-ads.txt.
- You didn't set up test devices.
- You didn't set up App Id inside your AndroidManifest.xml or Info.plist.

**Comment by Obhenimen** [comment]
I created the adunits 4 weeks ago.
I have set up my app-ads.txt
I set up have set up my test device in my admob account.
I have put my app id in my manifest.xml

**Comment by ShivamJoker** [comment]
I am getting this even on test ID
ca-app-pub-3940256099942544/1033173712

Possible Unhandled Promise Rejection (id: 1):
Error: No ad config.
Error: No ad config.

**Comment by Strapazzon** [comment]
I have same erro, after update to 1.2.1.

**Comment by ShivamJoker** [comment]
@Strapazzon was it working before this version ?

**Comment by Strapazzon** [comment]
> @Strapazzon was it working before this version ?

Yes, normaly.

**Comment by Obhenimen** [comment]
This should be very useful for those using test id. Please when using Google test id, Ensure that use also use Google app id in your android manifest file. Do not use your admob app id with google test id cos it won't work.

**Comment by ShivamJoker** [comment]
@Obhenimen it didn't work still gave the same error :/

**Comment by ShivamJoker** [comment]
@Strapazzon I tried the 1.2.0 and 1.1.2 still gave the same error

@wjaykim can you please help us out ?

**Comment by Obhenimen** [comment]
@ShivamJoker ok can you reproduce the code here.

**Comment by ShivamJoker** [comment]
The code is same as #49 (This library is broken with latest react native)

**Comment by wjaykim** [comment]
@Strapazzon You said the ad worked until previous version, can you check if the ads works after roll back to the previous version now?

Code 3 and error related "com.google.DummyAdapter" both means 
>The ad request was successful, but no ad was returned due to lack of ad inventory.

And those errors mean the code is correct, but admob returns no ads.

>This should be very useful for those using test id. Please when using Google test id, Ensure that use also use Google app id in your android manifest file. Do not use your admob app id with google test id cos it won't work.

In addition to the @Obhenimen's comment above, to receive test ads, you should add following line to app-ads.txt if you set up it:
```
google.com, pub-3940256099942544, DIRECT, f08c47fec0942fa0
```

Find out more solutions in https://stackoverflow.com/questions/33566485/failed-to-load-ad-3

**Comment by ShivamJoker** [comment]
@wjaykim the thing is I already have app ads setup and my production app is running ads on older version of react native library

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/23727670/140965250-969d19d6-02b8-4e92-aedc-100bdb59c37a.png">

Everything was fine until I upgraded stuffs

Also the stackoverflow link isn't helpful I have already done most of the stuffs

**Comment by ildfreelancer** [comment]
I got the same issue with v1.2.1
even I used google app id (in the official example) and test ad unit id, it doesn't work.

However the interesting here is after fixing the missing @babel/runtime on the example of this repository, the example works.

**Comment by wjaykim** [comment]
That's weird... I'll investigate more.

**Comment by ildfreelancer** [comment]
@wjaykim I created a new fresh project and it works
Seems like an issue with my project, but very hard to know why
"Error: Cannot find an ad network adapter with the name(s): com.google.DummyAdapter"

I will update you guys if found the root issue.

**Comment by ShivamJoker** [comment]
@ildfreelancer I have the same issue see #49 
Maybe try with running `react native clean project `

**Comment by ildfreelancer** [comment]
@Strapazzon Did you know the root of the issue?

**Comment by ildfreelancer** [comment]
@wjaykim 
when I try to use AdMob.isTestDevice().then((result) => console.log(result));
it shows false even I am using simulator with test ad unit
and const initializationStatus = await AdMob.getInitializationStatus();
show this

```
[{"description": "<GADAdapterStatus: 0x6000025e2a60; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterAppLovin", "state": false}, {"description": "<GADAdapterStatus: 0x6000025e2910; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventRewarded", "state": false}, {"description": "<GADAdapterStatus: 0x6000025f5ef0; state = Ready>", "name": "GADMobileAds", "state": true}, {"description": "<GADAdapterStatus: 0x6000025f5ec0; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterAdColony", "state": false}, {"description": "<GADAdapterStatus: 0x6000025a7d20; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterVungle", "state": false}, {"description": "<GADAdapterStatus: 0x6000025fca80; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterSample", "state": false}, {"description": "<GADAdapterStatus: 0x6000025a7d80; state = Not Ready;No such adapter in the application.>", "name": "MediationExample.SampleCustomEventNativeAdSwift", "state": false}, {"description": "<GADAdapterStatus: 0x6000025e8180; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterTapjoy", "state": false}, {"description": "<GADAdapterStatus: 0x600002592310; state = Not Ready;No such adapter in the application.>", "name": "MediationExample.SampleCustomEventInterstitialSwift", "state": false}, {"description": "<GADAdapterStatus: 0x6000025e22b0; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventBanner", "state": false}, {"description": "<GADAdapterStatus: 0x6000025a7f60; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventInterstitial", "state": false}, {"description": "<GADAdapterStatus: 0x600002591170; state = Not Ready;No such adapter in the application.>", "name": "MediationExample.SampleCustomEventBannerSwift", "state": false}, {"description": "<GADAdapterStatus: 0x6000025a7ea0; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventRewardedBasedVideoSwift", "state": false}, {"description": "<GADAdapterStatus: 0x6000025921c0; state = Not Ready;No such adapter in the application.>", "name": "SampleCustomEventNativeAd", "state": false}, {"description": "<GADAdapterStatus: 0x6000025e28e0; state = Not Ready;No such adapter in the application.>", "name": "GADMediationAdapterInMobi", "state": false}]
```

Does it stop working because using AdMob.setRequestConfiguration(config) ?

**Comment by ildfreelancer** [comment]
@ShivamJoker @wjaykim I believe this package conflicts with react-native-firebase, after install the package one by one to detect what the root of issue, I figured out that it got the issue after integrate firebase.
FYI

**Comment by manuhook** [comment]
@ildfreelancer I have the latest versions of react-native-firebase and react-native-admob/admob and everything works perfectly

**Comment by ildfreelancer** [comment]
@manuhook  I checked this thread
https://groups.google.com/g/google-admob-ads-sdk/c/Ce2iYsHPYCc?pli=1
and after I changed from test ad it to real ad id, it works

**Comment by ShivamJoker** [comment]
Intresting I'll give it a shot with real ad id

**Comment by ildfreelancer** [comment]
here is the proof.
![image](https://user-images.githubusercontent.com/31275803/141956091-ec3c8b89-341c-4de1-b2b5-433d5404084d.png)

**Comment by ShivamJoker** [comment]
@ildfreelancer oh nice I'm pretty sure that it's not firebase issue because I am not using it

**Comment by ildfreelancer** [comment]
I am not sure, however I think you should try following:
1/ Add this into you app-ads.txt in case you setup: google.com, pub-3940256099942544, DIRECT, f08c47fec0942fa0
2/ if it doesn't work with 1, try to test with real ad id and app id,  and don't click on the ads.

**Comment by ShivamJoker** [comment]
But now I have got another error 
@wjaykim any help with this one ?

```
The provided view controller is not being presented
```

**Comment by ShivamJoker** [comment]
BTW it seems to be working fine on android

**Comment by wjaykim** [comment]
> But now I have got another error @wjaykim any help with this one ?
> 
> ```
> The provided view controller is not being presented
> ```

Can you open new issue with this.
