### ISSUE TITLE
Error: Cannot find an ad network adapter with the name(s): com.google.DummyAdapter.

### ISSUE THREAD

**Issue by ShivamJoker** [react-native-admob/admob#49]
## Description
I am getting this error on iOS 15 while trying the minimal setup for interstitial ad with hooks

`Error: Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.`

### Expected behavior
The ad should show up in the latest version of react native on iOS

### Actual behavior & steps to reproduce
It is throwing error while trying to load the error

```jsx
    if (adLoaded) {
      show();
    } else {
      load();
    }
```

## Snack or minimal code example
```jsx
  const {load, adLoaded, show} = useInterstitialAd(TestIds.INTERSTITIAL_VIDEO);
```

## Package versions

- React Native: 0.66.1
- React Native AdMob: ^1.2.1
- Google Mobile Ads SDK(if specified): 
- Xcode: 13.1
- Java & Gradle: Gradle 4.2.2

## Affected platforms

- [ ] Android
- [x] iOS

**Comment by wjaykim** [comment]
Issue related to #48, see https://github.com/react-native-admob/admob/issues/48#issuecomment-964282043
