### ISSUE TITLE
Ability to enable/disable personalized ads

### ISSUE THREAD

**Issue by andkom** [react-native-admob/admob#5]
Ability to enable/disable personalized ads, specify user geolocation like in original firebase package wanted.

**Comment by wjaykim** [comment]
I'm preparing this and trying to make apis as same as previous firebase package.

**Comment by wjaykim** [comment]
Working this on branch [request-options](https://github.com/react-native-admob/admob/tree/request-options) and you can preview them.

**Comment by wjaykim** [comment]
Working done and available in new version.

**Comment by andkom** [comment]
thanks for your work! But after installing new version ad banner started to blink each re-render.

**Comment by wjaykim** [comment]
Have you declared requestOptions object inside your component? You have to declare it outside the react component.

**Comment by wjaykim** [comment]
Can you show your code?

**Comment by andkom** [comment]
Code:

```
<BannerAd
  unitId={unitId}
  size={size}
  requestOptions={{
    requestNonPersonalizedAdsOnly,
    location: [
      locationData.latitude,
      locationData.longitude,
    ],
    locationAccuracy: locationData.accuracy,
  }}
/>
```

I found the cause, it happened because locationData object was changing and banner re-rendered each time (in firebase package changing requestOptions didn't force banner to reload)

Solved the issue by caching location data. Thanks.
