### ISSUE TITLE
adDismissed, reward never change their values

### ISSUE THREAD

**Issue by eeslamadelll** [react-native-admob/admob#50]
## Description
`adDismissed` always false, and `reward` always undefined

### Expected those values to change

```
const {adLoaded, adDismissed, reward, adShowing, show} = useRewardedAd(
    TestIds.REWARDED,
    {
      requestOptions: {
        requestNonPersonalizedAdsOnly: true,
      },
    },
  );
  useEffect(() => {
    console.log('rewardrewardrewardrewardss', adDismissed, nameToShow);
    if (adDismissed) {
        /// do something
    }
  }, [adDismissed]);


```

- React Native: 0.66.0
- React Native AdMob: 1.1.0

**Comment by wjaykim** [comment]
Try this solution and feedback me if it not works. https://github.com/react-native-admob/admob/issues/51#issuecomment-964105866

**Comment by wjaykim** [comment]
Try version 1.2.1 and feedback me.

**Comment by eeslamadelll** [comment]
I was on version 1.2.1 and downgraded to 1.1.0 hoping it was working there but found the same behavior

**Comment by wjaykim** [comment]
Try latest version and reopen issue if it does not work.
