### ISSUE TITLE
Issues when use with react-native-admob-native-ads

### ISSUE THREAD

**Issue by TrungNguyen153** [react-native-admob/admob#55]
// unknow reason when install your package in my project cause function below not finish
                         
			 await AdManager.setRequestConfiguration({ // method from react-native-admob-native-ads
				trackingAuthorized,
				maxAdContentRating: 'G',
				tagForChildDirectedTreatment: false,
				tagForUnderAgeConsent: false,
			});

**Comment by wjaykim** [comment]
This is because the package react-native-admob-native-ads initializes sdk when call the function `setRequestOptions`, while this library initializes sdk automatically.
Replace `AdManager.setRequestOptions` to `AdMob.setRequestOptions`. `AdMob` is default export of this package.

**Comment by TrungNguyen153** [comment]
tks your response. i will try

**Comment by TrungNguyen153** [comment]
it work
