### ISSUE TITLE
Cannot read property 'requestAd' of null

### ISSUE THREAD

**Issue by OmkoBass** [react-native-admob/admob#56]
I want to show an interstitial add, but i'm always getting Cannot read property 'requestAd' of null.

The only thing I'm doing is this
```javascript
const interstitialAd = useInterstitialAd(
    "ca-app-pub-3940256099942544/1033173712",
    {}
  );
```

I'm sorry if this is a dumb question. Can someone give me an example or something.

**Comment by OmkoBass** [comment]
This code will work, but I can't show an add then.
```javascript
const interstitialAd = useInterstitialAd(null, {});
```
but if i place in any string for the ad id it will throw 
null is not an object (evaluating 'this.nativeModule.requestAd')

**Comment by marcoizzo** [comment]
+1

**Comment by OmkoBass** [comment]
I updated changed the test app id in android manifest to my app id and now i get a Maximum Depth Loop.

**Comment by OmkoBass** [comment]
I solved my problem by switching to this library: https://github.com/ammarahm-ed/react-native-admob-native-ads
You can implement any type of ad with the native ad format.

**Comment by wjaykim** [comment]
Try latest version and reopen issue if it does not work.
