### ISSUE TITLE
The provided view controller is not being presented

### ISSUE THREAD

**Issue by ShivamJoker** [react-native-admob/admob#59]
## Description

The provided view controller is not being presented while trying to load the ad on iOS
Continuing from #48 

## Snack or minimal code example
Just the example from docs 

## Package versions

- React Native: 0.66.1
- React Native AdMob: ^1.2.1
- Google Mobile Ads SDK(if specified): 
- Xcode: 13.1
- Java & Gradle: Gradle 4.2.2

## Affected platforms

- [ ] Android
- [x] iOS

**Comment by wjaykim** [comment]
>while trying to load the ad

Did you mean trying to show ad

**Comment by ShivamJoker** [comment]
Yes! The ad does load but when I call show it just throws the error

**Comment by wjaykim** [comment]
In what timing are you trying to show ad?

**Comment by ShivamJoker** [comment]
I have button when I click it loads the ad if `isLoaded` is true else it calls the `show`

**Comment by wjaykim** [comment]
Can you try installing library from [this branch](https://github.com/react-native-admob/admob/tree/top-viewcontroller) and tell me if it fixes.

**Comment by ShivamJoker** [comment]
Hey @wjaykim it seems to be working perfect in that branch
<img width="438" alt="image" src="https://user-images.githubusercontent.com/23727670/142734596-7b3de709-9d8e-4483-b55e-f1a3f43381e0.png">

Thanks ❤️
