### ISSUE TITLE
[ios] onSizeChange called with incorrect arguments for banner ads

### ISSUE THREAD

**Issue by mars-lan** [react-native-admob/admob#6]
```
  const onSizeChange = (size) => {
    console.info(`${JSON.stringify(size)}`);
  };

  <BannerAd
    size={BannerAdSize.ADAPTIVE_BANNER}
    unitId={unitId}
    onSizeChange={onSizeChange} />
```

The above snippet prints 
```
TypeError: JSON.stringify cannot serialize cyclic structures.
```

Both `size.width` & `size.height` are undefined.

**Comment by mars-lan** [comment]
The native side of the code looks a bit funky. You may find this tutorial useful: https://reactnative.dev/docs/native-components-ios

**Comment by wjaykim** [comment]
Fixed in [this commit](https://github.com/react-native-admob/admob/commit/980f9a0491f44b5c218a7572a4861611cee43bc4). I will release fixed version soon.

**Comment by wjaykim** [comment]
Fixed in version 1.0.1

**Comment by mars-lan** [comment]
Thanks for the quick fix!

**Comment by mars-lan** [comment]
@wjaykim same problem for `onAdFailedToLoad` which is supposed to return a stringifiable `Error`.

**Comment by wjaykim** [comment]
🤦🏻‍♂️ Sorry for inconvenient. Fix is released.
