### ISSUE TITLE
Build fails after updating to 1.3.0

### ISSUE THREAD

**Issue by SergiOnGit** [react-native-admob/admob#60]
## Description

After updating to version 1.3.0 from 1.2.1 I can't run app. Build fails with error:

`Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.work:work-runtime:{strictly 2.6.0}.
     Required by:
         project :app > project :react-native-admob_admob
      > Cannot find a version of 'androidx.work:work-runtime' that satisfies the version constraints:
           Dependency path 'mycustomappid:app:unspecified' --> 'mycustomappid:react-native-admob_admob:unspecified' --> 'androidx.work:work-runtime:{strictly 2.6.0}'
           Dependency path 'mycustomappid:app:unspecified' --> 'mycustomappid:react-native-admob_admob:unspecified' --> 'com.google.android.gms:play-services-ads:20.5.0' --> 'com.google.android.gms:play-services-ads-lite:20.5.0' --> 'androidx.work:work-runtime:2.7.0'

   > Could not resolve androidx.work:work-runtime:2.7.0.
     Required by:
         project :app > project :react-native-admob_admob > com.google.android.gms:play-services-ads:20.5.0 > com.google.android.gms:play-services-ads-lite:20.5.0
      > Cannot find a version of 'androidx.work:work-runtime' that satisfies the version constraints:
           Dependency path 'mycustomappid:app:unspecified' --> 'mycustomappid:react-native-admob_admob:unspecified' --> 'androidx.work:work-runtime:{strictly 2.6.0}'
           Dependency path 'mycustomappid:app:unspecified' --> 'mycustomappid:react-native-admob_admob:unspecified' --> 'com.google.android.gms:play-services-ads:20.5.0' --> 'com.google.android.gms:play-services-ads-lite:20.5.0' --> 'androidx.work:work-runtime:2.7.0'`

### Expected behavior
App should build and open.

### Actual behavior & steps to reproduce
Not building. Ends with error.

## Snack or minimal code example
It's not about code.

## Package versions

- React Native: 0.66.3
- React Native AdMob: 1.3.0
- Google Mobile Ads SDK(if specified):
- Xcode:
- Java & Gradle:

## Affected platforms

- [x] Android
- [ ] iOS - Not checked

**Comment by wjaykim** [comment]
Try [this solution](https://stackoverflow.com/a/69300246)

**Comment by SergiOnGit** [comment]
@wjaykim It worked.
