### ISSUE TITLE
Android SDK 31 required?

### ISSUE THREAD

**Issue by scottc5** [react-native-admob/admob#65]
The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
     AAR metadata file: C:\Users\corne\.gradle\caches\transforms-2\files-2.1\7697b9cb5e1a55cf53fc61fd3c9a78ba\work-runtime-2.7.0\META-INF\com\android\build\gradle\aar-metadata.properties
     
 Is there a reason androidx.work:work-runtime:2.7.0 needs to be used?  Just wondering because it requires the app to move to 31 instead of 30.

**Comment by wjaykim** [comment]
androidx.work:work-runtime:2.7.0 is included in Google Mobile Ads SDK from the version 20.5.0 it requires minCompileSdk should be 31. If you are not targeting 31, force androidx.work:work-runtime version to 2.6.0: [Link](https://stackoverflow.com/a/69300246/9579344)

**Comment by scottc5** [comment]
Thanks for the clarification as well as the work around option.
