### ISSUE TITLE
Interstistial ad always load on mounted even loadOnMounted = false ??

### ISSUE THREAD

**Issue by zoobibackups** [react-native-admob/admob#71]
I try to load interstitial ad on onPress evets but ads are always loaded on mounted. Check my code below

```
import { useInterstitialAd, TestIds } from '@react-native-admob/admob';

const App = () => {
    const { adLoaded, load} = useInterstitialAd(TestIds.INTERSTITIAL, {
      requestOptions: {
          loadOnMounted: false, // i am not loading ad on mounting
          loadOnDismissed: false
      },
    });

    useEffect(() => {
        if (adLoaded) {
          console.log("Loaded")   /// i never call the load function but still the add is loaded why?????
        }
    },[adLoaded])

   /* rest of the code*/
}
```

How to resolve this now???? 
Thanks.

**Comment by wjaykim** [comment]
I checked in example app but did not found the case. Can you show the part how you load the ad?

**Comment by wjaykim** [comment]
Your option object is wrong. It should be:
```js
{
  loadOnMounted: false,
  loadOnDismissed: false,
  requestOptions:{
    //...
  },
}
```
They should be declared outside of the `requestOptions` object.

**Comment by zoobibackups** [comment]
> Your option object is wrong. It should be:
> 
> ```js
> {
>   loadOnMounted: false,
>   loadOnDismissed: false,
>   requestOptions:{
>     //...
>   },
> }
> ```
> 
> They should be declared outside of the `requestOptions` object.

My bad, thank you its working now.
