### ISSUE TITLE
Metro Bundler failed

### ISSUE THREAD

**Issue by yash-vaghela21** [react-native-admob/admob#8]
Hello
Thank you for wonderful AdMob plugin.
after updating to latest version `1.0.1` it causing bundler error.

![Screenshot 2021-08-16 at 6 53 41 PM](https://user-images.githubusercontent.com/37238045/129570770-8363514b-9063-4f96-a841-9dc519053aef.png)

**Comment by wjaykim** [comment]
`AdManager` is replaced with default import `AdMob`. Check your imports. `import { AdManager } from '@react-native-admob/admob'` should be replaced with `import AdMob from '@react-native-admob/admob'`.

Sorry for not mentioning this in document for previous version users.

**Comment by yash-vaghela21** [comment]
@wjaykim ohh i didn't noticed.
Thank you for prompt response.
Solved✌️
