### ISSUE TITLE
Feature Request: add server side verification option for rewarded ad

### ISSUE THREAD

**Issue by andri9up** [react-native-admob/admob#80]
Hi, Thank you so much for amazing lib

Can you please add server side verification option for rewarded ad?

https://developers.google.com/admob/ios/api/reference/Classes/GADRewardedAd#/c:objc(cs)GADRewardedAd(py)serverSideVerificationOptions
https://developers.google.com/android/reference/com/google/android/gms/ads/rewarded/ServerSideVerificationOptions

Thanks

**Comment by danilaberentsev** [comment]
I'm in the middle of implementing rewarded ads. Did I get it right, you can't verify the user through admob callback without these options? How do I actually send user info from my front-end to my back-end with this callback, so I know who will be rewarded?
@wjaykim 

> Hi, Thank you so much for amazing lib
> 
> Can you please add server side verification option for rewarded ad?
> 
> https://developers.google.com/admob/ios/api/reference/Classes/GADRewardedAd#/c:objc(cs)GADRewardedAd(py)serverSideVerificationOptions https://developers.google.com/android/reference/com/google/android/gms/ads/rewarded/ServerSideVerificationOptions
> 
> Thanks

**Comment by wjaykim** [comment]
@danieltereschenko For now, you can implement your own api call to your server after user is rewarded.
But sooner I'll add server side verification option to Rewarded Ad.

**Comment by danilaberentsev** [comment]
isn't it a huge security flaw?

> @danieltereschenko For now, you can implement your own api call to your server after user is rewarded. But sooner I'll add server side verification option to Rewarded Ad.

**Comment by wjaykim** [comment]
@danieltereschenko Depending on your code.
I'v added support for ssv in #83.
