### ISSUE TITLE
About EEA Consent Form

### ISSUE THREAD

**Issue by sonivaibhav27** [react-native-admob/admob#84]
Thank you for building and maintaining this wonderful repo. How do i show EEA consent form if user is from EEA? 
@react-native-firebase/admob provide with google made consent form .

**Comment by manuhook** [comment]
This repo is working well with https://github.com/birgernass/react-native-ad-consent

**Comment by sonivaibhav27** [comment]
okay, Thank you for your reply.

**Comment by scaralfred** [comment]
How can we "delay" the sdk initialization?
Is there a method for that?
By law we should only collect EEA users personal data after they gave consent, but the sdk is loading at app a launch.

**Comment by scaralfred** [comment]
It's said but true if we use the Google UMP consent form, and the user does not consent, ads won't be showing at all
.
