### ISSUE TITLE
Android 12 - androidx.work issue

### ISSUE THREAD

**Issue by mscottwvc** [react-native-admob/admob#85]
In the package dependencies it specifies 
`api(group: "androidx.work", name: "work-runtime") {
        version {
            strictly "2.6.0"
        }
    }`
 The problem is that in this group I think there are some work packages that are incompatible with Android 12 at this 2.6.0 version, one of which appears to be : androidx.work:work-runtime-ktx
 So when using another package, for example react-native-firebase/auth it will crash because that package is restricted to 2.6.0 with android 12 FLAG_IMMUTABLE shenanigans mess.  In my quick testing changing this 2.7.1 resolves this.  I dont know if you could change this, or possibly only restrict certain packages and not the whole group.  I imagine you did this because you only wanted to release this package with what you have tested?  Thanks

**Comment by wjaykim** [comment]
I've removed the code in version 2.0.0. What package version are you using?

**Comment by mscottwvc** [comment]
Opps I forgot I never responded to this, I was using an older version, but 2.0.0 fixed it. Thanks!
