### ISSUE TITLE
AppOpenAd displayed above the interstialAd which is violation

### ISSUE THREAD

**Issue by zoobibackups** [react-native-admob/admob#86]
I want **showOnAppForeground** to true which is working fine, **BUT** when we resume the app on interstialAd then appOpenAd is shown **above** the InterstitialAd, which is **violation**.
```
import { AppOpenAdProvider, TestIds } from '@react-native-admob/admob';

    <AppOpenAdProvider
      unitId={TestIds.APP_OPEN}
      options={{ showOnColdStart: true, showOnAppForeground : true }}
    >
      {...........................................}
    </AppOpenAdProvider>
```

So how can we handle this using this library or avoid violation ??????

**Comment by tarouboy** [comment]
Use state to keep track if InterstialAd is opened?

**Comment by zoobibackups** [comment]
> Use state to keep track if InterstialAd is opened?

Yes I am tracking interstialAd but unable to track appOpenAd.
There is no show method of appOpenAd.

How I manage the state of appOpenAd????? like show appOpenAdd when interstitial is not open.

**Comment by zoobibackups** [comment]
> > Use state to keep track if InterstialAd is opened?
> 
> Yes I am tracking interstialAd but unable to track appOpenAd. There is no show method of appOpenAd.
> 
> How I manage the state of appOpenAd????? like show appOpenAdd when interstitial is not open.

@wjaykim any thoughts on this??

**Comment by wjaykim** [comment]
I think you should use global state to track if interstitial ad is opened and if then disable the app open ad until the ad is dismissed.

**Comment by zoobibackups** [comment]
AppOpenAd will never be shown or disabled while interstitial is showing. @wjaykim  Will this functionality be added to this library in future updates???

**Comment by wjaykim** [comment]
What does this mean?

> App open will never be shown or disabled while interstitial is shown

Add global state value whether another ad is showing and set `showOnForeground` option to `!adShowing` using the global state.

Currently I think adding the logic is too much for this library and it is app developer's part to manage the violation as adding the logic may restrict customization in some cases.

**Comment by zoobibackups** [comment]
Ok never mind, i will handle this using global state. 
Thanks alot!
