### ISSUE TITLE
App crash on start up (only on emulator)

### ISSUE THREAD

**Issue by brobin002** [react-native-admob/admob#89]
## Description
App crash on start up (only on emulator) with the error: 

AndroidRuntime: java.lang.LinkageError: Method java.lang.Object com.google.android.gms.internal.ads.vq3.a() overrides final method in class Lcom/google/android/gms/internal/ads/mq3;

## Package versions

- React Native: 0.64.2
- React Native AdMob: 2.0.0
- Java & Gradle: 4.1.0

## Affected platforms

- Android

**Comment by buraka** [comment]
I have the same issue. Is there any update for this? I tried the 2.0.1 version too but the problem isn't solved.

**Comment by wjaykim** [comment]
Could you guys try upgrading your projects' gradle version and see if it fixes.

Related issue: https://github.com/googleads/googleads-mobile-flutter/issues/471#issuecomment-1037144582

**Comment by brobin002** [comment]
Upgrading my project gradle fixes the issue! Thanks!

**Comment by mcama** [comment]
> Upgrading my project gradle fixes the issue! Thanks!

Hi! What gradle version did you update to? And what process did follow to perform the update? 

Thanks in advance!
