### ISSUE TITLE
[RewardedAd] `loadOnMounted: false` performance issue. 

### ISSUE THREAD

**Issue by JeffGuKang** [react-native-admob/admob#90]
### Expected behavior

Load rewarded ad smoothly with `loadOnMounted: true` option when we create RewardedAd instance. 
Very laggy in old iPhone. (Tested in 6s)

## Snack or minimal code example

The code causes performance issue.
```
  const rewardedAdRef = useRef(
    RewardedAd.createAd(AD_ID, {
      loadOnMounted: true,
      loadOnDismissed: true,
    }),
  )
```

It makes to solve the performance issue. 
```
      loadOnMounted: false,
```

And I called `load` in useEffect.

## Package versions

- React Native: 0.66.3
- React Native AdMob: 1.5.1,

## Affected platforms

- [ ] Android
- [x] iOS

**Comment by trizin** [comment]
Same issue on android.

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
