### ISSUE TITLE
new react native project won't compile for android

### ISSUE THREAD

**Issue by vu-dang** [react-native-admob/admob#92]
I getting this error:
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.

After creating a new project and add this package

npx react-native init myproject
yarn add @react-native-admob/admob
npx react-native run-android

It looks like this package requires SDK 31 but the current version of react-native is using SDK 30.

**Comment by wjaykim** [comment]
> It looks like this package requires SDK 31 but the current version of react-native is using SDK 30.

Yes, so you need to set the sdk version to 31. Then it will compile without error.
