### ISSUE TITLE
Can't get serverSideVerificationOptions data in server side callback

### ISSUE THREAD

**Issue by Ggayane** [react-native-admob/admob#94]
Hi, I'm trying to implement rewarded adds (using both `RewardedAd` and `useRewardedAd`), passing `requestOptions` with `serverSideVerificationOptions`, passing userId but don't get any data when my server side verification callback function fires. 
Can you please tell what can be the problem connected with?

**Comment by wjaykim** [comment]
Hi, did you resolved the issue? What was the problem?

**Comment by Ggayane** [comment]
Hi, yes, I'm not sure if it's a bug or not, but I was calling `RewardedAd.createAd()` with all needed options (with `serverSideVerificationOptions`) after which I was calling `load()` method without any option, because I've already had the created ad with needed options.

Calling load method with options solved the problem. The final code example:

```js
  const rewardedAd = RewardedAd.createAd(unitId);
  await rewardedAd.load({
    serverSideVerificationOptions: {
      userId,
    },
  });
  return rewardedAd.show();
```
