### ISSUE TITLE
Problem with M1 (Macbook 2021 Pro 14 inch)

### ISSUE THREAD

**Issue by Acetyld** [react-native-admob/admob#95]
Hallo

We cant get any app working on a M1 with React-Native admob
We keep getting:
```

/Users/acetyld/PhpstormProjects/appname/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'boost-for-react-native' from project 'Pods')
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is this a known issue?

**Comment by wjaykim** [comment]
> in target 'boost-for-react-native' from project 'Pods'

The log seems to be not related with this library.

**Comment by ildfreelancer** [comment]
check my gist here: https://gist.github.com/ildfreelancer/c161628115e590749599ceb6e623125c

follow step 1.
@Acetyld

**Comment by andreilikewise** [comment]
@Acetyld Two issues here...
1. The iOS Simulator Target is below the supported range (9.0 - 15.2.99). So increasing the simulator target within that range should make the warning go away.
2. It seems there is a package/dependency that isn't yet supported for ARM64 Macs, not sure which one from the log. In that case you may have to run Xcode under Rosetta.

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
