### ISSUE TITLE
After  rewardedAd.load(), the ad screen or Alert can't display normally. 

### ISSUE THREAD

**Issue by StanLee12** [react-native-admob/admob#96]
## Description

When i set loadOnMounted and loadOnDismissed is false, i use rewarded.load() instead of it， But when rewardedAd.laod() return the Promise, The ad screen or Alert just display for a while. About several  millisecond.

### Expected behavior

I excepted after rewardedAd.load(), the ad screen or alert can display normally.

## Snack or minimal code example

``` 
try {
        this.setState({ isLoading: true });
        this.adManager.setIsRewarded(false);
        await this.adManager.loadRewardedAd();
        this.adManager.showRewardedAd();
    } catch (adError) {
        Alert.alert(adError.userInfo.message);
    } finally {
        this.setState({ isLoading: false });
    }
```

## Package versions

package version 2.0.0

- React Native: 0.61.5
- React Native AdMob: 2.0.0
- Google Mobile Ads SDK(if specified):
- Xcode: 12.5
- Java & Gradle:

## Affected platforms

- [ ] Android
- [x] iOS

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
