### ISSUE TITLE
Implementation of AdMob mediation 

### ISSUE THREAD

**Issue by dima-mamaev** [react-native-admob/admob#97]
We want to use mediation to maximize our fill rate and increase monetization, but I couldn't find any guide/recommendations on how to do it.

**Comment by zoobibackups** [comment]
> We want to use mediation to maximize our fill rate and increase monetization, but I couldn't find any guide/recommendations on how to do it.

@[dima-mamaev](https://github.com/dima-mamaev) Just add the mediation dependencies in you gradle file, it works.

`e.g implementation 'com.google.ads.mediation:facebook:6.8.0.0' // for facebook mediation`

Just that from the app side.

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
