### ISSUE TITLE
Support Expo EAS build via plugin config?

### ISSUE THREAD

**Issue by giautm** [react-native-admob/admob#99]
Hi, Would you like to support Expo EAS build via plugin config? I will send a PR for that support.

**Comment by wjaykim** [comment]
# This library is deprecated. Use [react-native-google-mobile-ads][0] instead.

Please migrate to the [new library][0] if you were using this library as this library is no longer maintained. Now more stronger features are available in the [new library][0].

[0]: https://github.com/invertase/react-native-google-mobile-ads
